#!/bin/bash
#
# Just some simple aliases to make life easier.
#


alias ls='ls --color=auto'
alias cpa='rsync -avzP'
alias enable_alert='PS1="$PS1\a"'

# alias for use with git
alias lsd='git log --graph --decorate --pretty=oneline --abbrev-commit --all'

# cal alias
alias calm='cal -w -m -3'

alias mutt='~/.scripts/mutt_launcher'
