#!/bin/bash
#
#

export EDITOR=vim
export BROWSER=dwb
export TRANSPARENCY=95

export PATH=${PATH}:~/bin
export PATH=${PATH}:~/.bin
export PATH=${PATH}:~/.scripts

export PATH=${PATH}:~/android/android-sdk-linux/tools
export PATH=${PATH}:~/android/android-sdk-linux/platform-tools
export JAVA_HOME='/usr/lib/jvm/java-default-runtime'
#export JAVA_HOME='/usr/lib/jvm/java-7-openjdk' #override for android studio
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on' #fix for intellji

export PATH="$HOME/.dynamic-colors/bin:$PATH"
