#!/bin/bash
#
#

export EDITOR=vim
export BROWSER=vimbn
export TRANSPARENCY=95

export VDPAU_DRIVER=va_gl

export PATH=${PATH}:~/bin
export PATH=${PATH}:~/.bin
export PATH=${PATH}:~/.scripts

export PATH=${PATH}:~/android/android-sdk-linux/tools
export PATH=${PATH}:~/android/android-sdk-linux/platform-tools
export JAVA_HOME='/usr/lib/jvm/java-default-runtime'
export _JAVA_AWT_WM_NONREPARENTING=1

export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh;
