#!/bin/bash
#
# My small mutt account switcher preloader script.
#

declare -i i=0
declare -a array

printf "Choose a configuration file:\n--\n"

for a in ~/.mutt/*.acc
do
    if [[ -f $a ]]; then
        let i++
        array[i]=$a
        echo $i: $a
    fi
done

printf "\n"
read -p "Select one of the above: " input

if [[ $input = [1-$i] ]] ; then
    export MUTT_SOURCE=${array[$input]}
    \mutt
else
    echo "#### Bad input ####"
fi

exit
