#!/bin/bash
#
# vimb wrapper script for generating a disposable vimb session.
#

VIMBN=~/develop/priv/vimb/src/vimbn
SCRIPTPATH=`dirname $(readlink -f $0)`

RAND=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`

$VIMBN -p $RAND -c $SCRIPTPATH/vimbn.config

# cleanup
rm -r ~/.config/vimbn/$RAND
